### PR TITLE
Style and functionality fixes

### LINKED ISSUE #38: Button outline styles not inheriting colors

### LINKED ISSUE #39: Body text wrong font
Content paragraph and list item font is wrong.

### PR DESCRIPTION
**Pull request by ChaosExAnima**
This PR fixes a few issues with the current theme implementation:
* Fixes #38.
* Fixes #39.
* Removes controls from Customizer that aren't relevant.
* Forces some colors to be correct.
* Fixes header issues with the default template.
* Updates design for homepage cover not to show logo.
* Fixes overflow menu colors.
* Makes editor styles more consistent.
* Makes common colors stylesheet.

### CODE REVIEW

File: functions.php [hunk 1]
```diff
@@ -159,3 +183,25 @@ function filter_logo( string $html ) : string {
...
+ */
+function register_customizer( WP_Customize_Manager $wp_customize ) : void {
+	$controls = [
+		'retina_logo',
+		'accent_hue_active',
+		'enable_header_search',
+		'cover_template_separator_1',
+		'cover_template_overlay_background_color',
+		'cover_template_overlay_text_color',
+		'cover_template_overlay_opacity',
```
Comment (jffng) [inline functions.php:202]: Seems like all that is left is the `header_footer_background_color` control. Is there a good reason to leave this enabled?

File: style-editor.css [hunk 2]
```diff
@@ -1,17 +1,29 @@
-
 /*--------------------------------------------------------------
 # Editor Styles 
 #
 # This is the place to enter any custom overrides or structural 
 # styles for the block editor.
 --------------------------------------------------------------*/
 
+/*
+This multiplier is to account for the changes in width between the editor and the front end.
```
Comment (jffng) [inline style-editor.css:9]: Maybe it's just me, but scaling the type sizes between the editor and front-end seems counterintuitive. As a content creator, I would expect that the size I'm being shown in the editor is what appears on my site, especially if you're giving me a way to set the type size explicitly via the block settings. But I may be biased here because I spend all day trying to make themes where the editor experience mirrors the front end 😅.

Also, the `has-x-font-size` rules aren't respected when you use the change block's font size via "Text Settings" due to the styles being inlined:

Screen Shot 2020-05-12 at 10 09 08 PM

File: functions.php (hunk 1 above)
Comment (ChaosExAnima) [reply functions.php:206]: Fair enough. Resolved in b4da60f6f030cd5da0fb37d19f2e1bd7b73f4482.

File: style-editor.css (hunk 2 above)
Comment (ChaosExAnima) [reply style-editor.css:9]: I disabled custom header sizes in b2323aa4caf05d2d5692838b383d16143a4698c4, so that should take care of inlining.

Regarding mirroring the experience, I'd love to have things be identical, but I've seen a lot of issues with Gutenberg when the code sets the editor's width to 700px. Is that something you know how to work around?

Comment (ChaosExAnima) [reply style-editor.css]: So I re-read the Gutenberg theming guide, and noticed there's https://developer.wordpress.org/block-editor/developers/themes/theme-support/#changing-the-width-of-the-editor. I implemented that in 3349d3, so we should be good here!
